config/routes.rb
DemoApp::Application.routes.draw do
  resources :picoposts

  resources :users

end

app/models/picopost.rb
class Picopost < ActiveRecord::Base
	belongs_to :user
	validates :content, :length => { :maximum => 100 } 
	validates_presence_of :user_id
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :picoposts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/picoposts_controller.rb
class PicopostsController < ApplicationController
  # GET /picoposts
  # GET /picoposts.xml
  def index
    @picoposts = Picopost.all

  end

  # GET /picoposts/1
  # GET /picoposts/1.xml
  def show
    @picopost = Picopost.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @picopost }
    end
  end

  # GET /picoposts/new
  # GET /picoposts/new.xml
  def new
    @picopost = Picopost.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @picopost }
    end
  end

  # GET /picoposts/1/edit
  def edit
    @picopost = Picopost.find(params[:id])
  end

  # POST /picoposts
  # POST /picoposts.xml
  def create
    @picopost = Picopost.new(params[:picopost])

    respond_to do |format|
      if @picopost.save
        format.html { redirect_to(@picopost, :notice => 'Picopost was successfully created.') }
        format.xml  { render :xml => @picopost, :status => :created, :location => @picopost }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @picopost.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /picoposts/1
  # PUT /picoposts/1.xml
  def update
    @picopost = Picopost.find(params[:id])

    respond_to do |format|
      if @picopost.update_attributes(params[:picopost])
        format.html { redirect_to(@picopost, :notice => 'Picopost was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @picopost.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /picoposts/1
  # DELETE /picoposts/1.xml
  def destroy
    @picopost = Picopost.find(params[:id])
    @picopost.destroy

    respond_to do |format|
      format.html { redirect_to(picoposts_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.xml
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.xml
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @user }
    end
  end

  # GET /users/new
  # GET /users/new.xml
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.xml
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to(@user, :notice => 'User was successfully created.') }
        format.xml  { render :xml => @user, :status => :created, :location => @user }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @user.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.xml
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to(@user, :notice => 'User was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @user.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.xml
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to(users_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/picoposts_helper.rb
module PicopostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DemoApp</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/picoposts/_form.html.erb
<%= form_for(@picopost) do |f| %>
  <% if @picopost.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@picopost.errors.count, "error") %> prohibited this picopost from being saved:</h2>

      <ul>
      <% @picopost.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_field :content %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.text_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/picoposts/edit.html.erb
<h1>Editing picopost</h1>

<%= render 'form' %>

<%= link_to 'Show', @picopost %> |
<%= link_to 'Back', picoposts_path %>

app/views/picoposts/index.html.erb
<h1>Listing picoposts</h1>

<table>
  <tr>
    <th>Content</th>
    <th>User</th>
    <th>When</th>
	<th></th>
    <th></th>
    <th></th>
  </tr>

<% @picoposts.each do |picopost| %>
  <tr>
    <td><%= picopost.content %></td>
    <td><%= picopost.user_id %></td>
    <td><%= picopost.updated_at %></td>
    
    <td><%= link_to 'Show', picopost %></td>
    <td><%= link_to 'Edit', edit_picopost_path(picopost) %></td>
    <td><%= link_to 'Destroy', picopost, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Picopost', new_picopost_path %>

app/views/picoposts/new.html.erb
<h1>New picopost</h1>

<%= render 'form' %>

<%= link_to 'Back', picoposts_path %>

app/views/picoposts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Content:</b>
  <%= @picopost.content %>
</p>

<p>
  <b>User:</b>
  <%= @picopost.user_id %>
</p>


<%= link_to 'Edit', edit_picopost_path(@picopost) %> |
<%= link_to 'Back', picoposts_path %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Email</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.name %></td>
    <td><%= user.email %></td>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Delete', user, :confirm => 'Are you really really sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @user.name %>
</p>

<p>
  <b>Email:</b>
  <%= @user.email %>
</p>


<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>